version: '3.1'

services:
  drupal:
    container_name: drupal
    image: drupal
    ports:
      - "80:80"
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    networks:
      - drupal_net

  postgres:
    container_name: psql
    image: postgres
    environment:
      POSTGRES_PASSWORD: awais123
    volumes:
      - psql_data:/var/lib/postgresql/data
    networks:
      - drupal_net

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  psql_data:

networks:
  drupal_net:
